spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customer_service
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
  devtools:
    livereload:
      enabled: true
