server:
  port: 7979
  application:
    name: customer-service

aws:
  dynamodb:
    tableName: "Customer"
    secretKey: "12345"
    accessKey: "local"
    endpoint: "http://localhost:8000"
    region: "us-west-2"

security:
  token:
    enabled: true
    bypass: "test"
    keyFilePath: "secrets/customer-private.key"

